version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./credentials:/app/credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/choosee-461610-f105153b5594.json
      - DATABASE_URL=postgres://user:password@db:5432/weats_db
      - SECRET_KEY=your-secret-key
      - DEBUG=False
      - ALLOWED_HOSTS=your-domain.com,www.your-domain.com
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=weats_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:
